# Generated by Django 2.1.2 on 2018-10-12 13:15

from django.db import migrations, models
import nt_core.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserApiRecordHistory',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('create_time', models.BigIntegerField(default=nt_core.models.get_current_time_bigint)),
                ('update_time', models.BigIntegerField(default=nt_core.models.get_current_time_bigint)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('app_url', models.CharField(blank=True, max_length=100, null=True)),
                ('path_info', models.CharField(blank=True, max_length=500, null=True)),
                ('query_string', models.CharField(blank=True, max_length=500, null=True)),
                ('post_data', models.CharField(blank=True, max_length=500, null=True)),
                ('remote_addr', models.GenericIPAddressField(blank=True, null=True)),
                ('method', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'api_record_history',
            },
        ),
    ]
