# Generated by Django 2.1.2 on 2018-10-13 18:14

from django.db import migrations, models
import jsonfield.fields
import nt_core.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatResultData',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('create_time', models.BigIntegerField(default=nt_core.models.get_current_time_bigint)),
                ('update_time', models.BigIntegerField(default=nt_core.models.get_current_time_bigint)),
                ('appid', models.IntegerField(blank=True, null=True)),
                ('algorithm_name', models.CharField(blank=True, max_length=50, null=True)),
                ('start_time', models.BigIntegerField()),
                ('end_time', models.BigIntegerField()),
                ('result_data', jsonfield.fields.JSONField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cat_result_data',
            },
        ),
    ]
