# Generated by Django 2.1.2 on 2018-12-13 21:39

from django.conf import settings
from django.db import migrations, models
import nt_core.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('nt_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedbackMessage',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=40, primary_key=True, serialize=False)),
                ('create_time', models.BigIntegerField(default=nt_core.models.get_current_time_bigint)),
                ('update_time', models.BigIntegerField(default=nt_core.models.get_current_time_bigint)),
                ('message_type', models.IntegerField(choices=[(1, '咨询'), (2, '算法反馈'), (3, '建议')], default=1, help_text='反馈类型: 1(咨询),2(算法反馈),3(建议)', verbose_name='反馈类型')),
                ('topic', models.CharField(default='', max_length=100, verbose_name='主题')),
                ('message', models.TextField(default='', help_text='反馈内容', verbose_name='反馈内容')),
                ('file', models.FileField(help_text='上传的文件', upload_to='message/images/', verbose_name='上传的文件')),
                ('user', models.ForeignKey(on_delete=True, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户反馈',
                'verbose_name_plural': '用户反馈',
            },
        ),
    ]
