# Generated by Django 2.1.7 on 2019-05-23 07:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('messager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间'),
        ),
    ]
