# Generated by Django 2.1.7 on 2019-02-28 03:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='verb',
            field=models.CharField(
                choices=[('L', '赞了'), ('C', '评论了'), ('F', '收藏了'), ('A', '回答了'), ('W', '接受了回答'), ('R', '回复了'), ('I', '登录'), ('O', '退出')], max_length=1,
                verbose_name='通知类别'),
        ),
    ]
