# Generated by Django 2.1.7 on 2019-05-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('notifications', '0002_auto_20190228_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='object_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='slug',
            field=models.SlugField(blank=True, max_length=80, null=True, verbose_name='(URL)别名'),
        ),
    ]
